#pragma once

enum DetectionMode {
	FACIAL_RECOGNITION = 0,
	PEDESTRIAN_DETECTION = 1,
};

enum InputMode {
	CAMERA_INPUT = 0,
	FILE_VIDEO_INPUT = 1
};

enum ModelUsed {
	FACENET = 0,
	PERSON_VEHICLE_BIKE_DETECTION_CROSSROAD_0078 = 1,
	SSD_MOBILENET = 2
};